### ISSUE TITLE
LoggerUtils

### ISSUE THREAD

**Issue by xmoulin** [jeetemplates/jsf-spring-mybatis#1]
Start / End method peuvent etre positionnée dans un intercepteur Spring: en mode proxy, interception de toutes les entrées/sortie sur les classes de service/domaine/dao.

Est-ce que toutes tes log n'ont pas comme "chemin" loggerUtils, comme tu encapsules le module de log?
si tu prends un "ConversionPattern" du type " [%-5p] [%d{dd MMM HH:mm:ss}] [%c] - %m%n"
ton %c affichera toujours loggerUtils. ?
Sinon, c'est top ;o)

**Comment by paoesco** [comment]
Spring AOP est la prochaine amélioration de ces templates.

Effectivement les logs ne sont pas correctement configurés. Avec AOP ça sera ok

**Comment by paoesco** [comment]
Si tu te sens d'attaque, tu peux toujours proposer un pull request :)

**Comment by xmoulin** [comment]
Je recherche un template avec du Spring MVC en front ;o)

**Comment by paoesco** [comment]
je suis en train de le faire. Tu attends fin de week-end et tu pourras l'avoir (sans Spring AOP).
Avec Spring AOP, ça sera plutôt fin de semaine prochaine.

Edit : ce sera du springmvc / spring / hibernate et spring mvc / spring / mybatis
